{% set name = "openh264" %}
{% set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/cisco/openh264/archive/v{{ version }}.tar.gz
  sha256: e4e5c8ba48e64ba6ce61e8b6e2b76b2d870c74c270147649082feabb40f25905

build:
  number: 1
  skip: true  # [not win]
  run_exports:
    # new so names and compatibility changes on minor version
    # https://abi-laboratory.pro/?view=timeline&l=openh264
    - {{ pin_subpackage('openh264', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - autotools_clang_conda  # [win]
    - pkg-config
    - nasm
    - make  # [unix]
    - m2-make       # [win]
    - m2-sed        # [win]
    - m2-coreutils  # [win]
    - m2-gawk       # [win]
  host:
    - zlib

test:
  commands:
    - h264enc -h
    - h264dec | grep welsdec.cfg       # [unix]
    - h264dec | findstr welsdec.cfg    # [win]
    - test -f $PREFIX/lib/libopenh264${SHLIB_EXT}                         # [unix]
    - if not exist %PREFIX%\\Library\\bin\\openh264.dll exit 1            # [win]
    - if not exist %PREFIX%\\Library\\lib\\openh264.lib exit 1            # [win]
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\openh264.pc exit 1  # [win]

about:
  home: http://www.openh264.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenH264 is a codec library which supports H.264 encoding and decoding
  dev_url: https://github.com/cisco/openh264
  doc_url: https://github.com/cisco/openh264

extra:
  recipe-maintainers:
    - 183amir
    - sdvillal
    - hmaarrfk
